In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
data = pd.read_csv("../06_machine_learning/data/house_test.csv")
data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [ ]:
data3 = data.copy()

In [ ]:
data = pd.get_dummies(data)
data

In [ ]:
data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]

In [ ]:
data

In [ ]:
import joblib

In [ ]:
rs = joblib.load("./model/iowa_robustscaler.joblib")
data_scaled = rs.transform(data)
data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
data_scaled

In [ ]:
from tensorflow.keras.models import load_model

In [ ]:
model = load_model("./model/iowa_house792__925173184.0000.keras")
pred = model.predict(data_scaled)
pred = pd.DataFrame(pred, columns=['test_pred'])
pred

# 함수로 테스트 데이터 처리하기

In [ ]:
def data_preporcessing(data):
    data = pd.get_dummies(data)
    data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]
    rs = joblib.load("./model/iowa_robustscaler.joblib")
    data_scaled = rs.transform(data)
    data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
    return data_scaled

In [ ]:
def prediction(data):
    model = load_model("./model/iowa_house792__925173184.0000.keras")
    pred = model.predict(data)
    pred = pd.DataFrame(pred, columns=['test_pred'])
    return pred

In [ ]:
data2 = pd.read_csv("../06machine_learning/data/house_test.csv")
result = data_preporcessing(data2)
result

In [ ]:
prediction(result)

# XGBR 모델 불러와서 분석하기

In [ ]:
data3 = pd.read_csv("../06machine_learning/data/house_test.csv")

In [ ]:
data3.columns

In [ ]:
data3 = data3[['MSSubClass', 'MSZoning', 'LotFrontage', 'LotArea', 'Street',
       'LotShape', 'LandContour', 'Utilities', 'LotConfig', 'LandSlope',
       'Neighborhood', 'Condition1', 'Condition2', 'BldgType', 'HouseStyle',
       'OverallQual', 'OverallCond', 'YearBuilt', 'YearRemodAdd', 'RoofStyle',
       'RoofMatl', 'Exterior1st', 'Exterior2nd', 'MasVnrArea', 'ExterQual',
       'ExterCond', 'Foundation', 'BsmtQual', 'BsmtCond', 'BsmtExposure',
       'BsmtFinType1', 'BsmtFinSF1', 'BsmtFinType2', 'BsmtFinSF2', 'BsmtUnfSF',
       'TotalBsmtSF', 'Heating', 'HeatingQC', 'CentralAir', 'Electrical',
       '1stFlrSF', '2ndFlrSF', 'LowQualFinSF', 'GrLivArea', 'BsmtFullBath',
       'BsmtHalfBath', 'FullBath', 'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr',
       'KitchenQual', 'TotRmsAbvGrd', 'Functional', 'Fireplaces', 'GarageType',
       'GarageYrBlt', 'GarageFinish', 'GarageCars', 'GarageArea', 'GarageQual',
       'GarageCond', 'PavedDrive', 'WoodDeckSF', 'OpenPorchSF',
       'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea', 'MiscVal',
       'MoSold', 'YrSold', 'SaleType', 'SaleCondition']]

In [ ]:
data3 = pd.get_dummies(data3)
data3

# joblib => 데이터직렬화

In [ ]:
X2_columns = joblib.load("./model/X2columns.joblib")
X2_columns

In [ ]:
for col in X2_columns:
    if col not in data3.columns:
        data3[col] = False
        
#이름 빠져있으면 맞춰주고, 순서까지 맞춰줌

In [ ]:
len(data3.columns) == len(X2_columns)

In [ ]:
data3 = data3[X2_columns]
data3

In [ ]:
rs2 = joblib.load("./model/robust_scaler_xgb.joblib")
data3_scaled = rs2.transform(data3)
data3_scaled = pd.DataFrame(data3_scaled, columns=data3.columns)
data3_scaled

# joblib으로 저장한 scaler, model 불러오기

In [6]:
import joblib

In [7]:
robust_scaler = joblib.load("./model/iowa_robustscaler.joblib")

In [18]:
data2_scaled = robust_scaler.transform(data2_selected)
data2_scaled = pd.DataFrame(data2_scaled, columns=data2_selected.columns)
data2_scaled

,OverallQual,GrLivArea,GarageCars,YearBuilt,FullBath,TotalBsmtSF,1stFlrSF,ExterQual_Gd,YearRemodAdd,Fireplaces,KitchenQual_TA,GarageFinish_Unf,ExterQual_TA
0,-0.5,-0.877559,-1.0,-0.260870,-1.0,-0.217910,-0.375061,0.0,-0.891892,-1.0,0.0,1.0,0.0
1,0.0,-0.208575,-1.0,-0.326087,-1.0,0.671642,0.475209,0.0,-0.972973,-1.0,-1.0,1.0,0.0
2,-0.5,0.254925,0.0,0.521739,0.0,-0.126368,-0.312224,0.0,0.108108,0.0,0.0,0.0,0.0
3,0.0,0.216300,0.0,0.543478,0.0,-0.130348,-0.316151,0.0,0.108108,0.0,-1.0,0.0,0.0
4,1.0,-0.284280,0.0,0.413043,0.0,0.574129,0.378989,1.0,-0.054054,-1.0,-1.0,0.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-1.0,-0.574739,-2.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,0.0,0.0
1455,-1.0,-0.574739,-1.0,-0.065217,-1.0,-0.886567,-1.062347,0.0,-0.648649,-1.0,0.0,1.0,0.0
1456,-0.5,-0.370800,0.0,-0.282609,-1.0,0.462687,0.269023,0.0,0.054054,0.0,0.0,1.0,0.0
1457,-0.5,-0.763229,-2.0,0.413043,-1.0,-0.158209,-0.229750,0.0,-0.054054,-1.0,0.0,0.0,0.0
1458,0.5,0.828119,1.0,0.434783,0.0,0.008955,-0.178694,0.0,0.000000,0.0,0.0,0.0,0.0

In [20]:
def data_preprocessing(data):
    data=pd.get_dummies(data)
    data = data[['OverallQual', 'GrLivArea', 'GarageCars', 'YearBuilt', 'FullBath',
       'TotalBsmtSF', '1stFlrSF', 'ExterQual_Gd', 'YearRemodAdd', 'Fireplaces',
       'KitchenQual_TA', 'GarageFinish_Unf', 'ExterQual_TA']]
    rs = robust_scaler = joblib.load("./model/iowa_robustscaler.joblib")
    data_scaled = rs.transform(data)
    data_scaled = pd.DataFrame(data_scaled, columns=data.columns)
    return data_scaled

In [21]:
test_data = data_preprocessing(data)

In [3]:
from tensorflow.keras.models import load_model

In [4]:
model = load_model("./model/iowa_house792__925173184.0000.keras")

2024-09-11 15:06:11.518778: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-09-11 15:06:11.520542: I tensorflow/c/logging.cc:34] DirectML: creating device on adapter 0 (AMD Radeon(TM) RX Vega 11 Graphics)
2024-09-11 15:06:11.618749: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:306] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-09-11 15:06:11.618799: W tensorflow/core/common_runtime/pluggable_device/pluggable_device_bfc_allocator.cc:28] Overriding allow_growth setting because force_memory_growth was requested by the device.
2024-09-11 15:06:11.618824: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:272] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 15603 MB memory) -> physical PluggableDevice (device: 0, name: DML, pci bus id: <undefined>)

In [27]:
test_pred = model.predict(test_data)
test_pred = pd.DataFrame(test_pred, columns=["test_pred"])

46/46 [==============================] - 0s 4ms/step

In [28]:
test_pred

          test_pred
0     109955.562500
1     146410.140625
2     167009.890625
3     195284.078125
4     200004.109375
...             ...
1454  113808.890625
1455  108089.812500
1456  139701.765625
1457  128684.101562
1458  239234.031250

[1459 rows x 1 columns]

In [19]:
# from sklearn.preprocessing import MinMaxScaler
# import numpy as np

# # 첫 번째 경우: 1과 10000
# data1 = np.array([[1], [5000], [10000]])
# scaler1 = MinMaxScaler()
# scaled_data1 = scaler1.fit_transform(data1)

# # 두 번째 경우: 1과 100000
# data2 = np.array([[1], [50000], [100000]])
# scaler2 = MinMaxScaler()
# scaled_data2 = scaler2.fit_transform(data2)

# print("1과 10000을 변환한 결과:")
# print(scaled_data1)

# print("\n1과 100000을 변환한 결과:")
# print(scaled_data2)

1과 10000을 변환한 결과:
[[0.        ]
 [0.49994999]
 [1.        ]]

1과 100000을 변환한 결과:
[[0.      ]
 [0.499995]
 [1.      ]]